const servicesData = [
    {
      id: 1,
      title: 'Book Basketball Court',
      location: 'New York',
      details: 'Book a state-of-the-art basketball court for your games and practice sessions.',
      image: '../images/Basketball.jpeg',
      score: 8.7,
      price: 50,
      originalPrice: null,
      available: true,
    },
    {
      id: 2,
      title: 'Rent a Pool',
      location: 'Boston',
      details: 'Rent a private pool for parties, events, or personal use.',
      image: '/images/Pool.avif',
      score: 9.2,
      price: 180,
      originalPrice: 200,
      available: true,
    },
    {
      id: 3,
      title: 'Rent a Place for Party',
      location: 'Miami',
      details: 'Rent a spacious and well-equipped venue for your parties and events.',
      image: '/images/Party.jpeg',
      score: 8.9,
      price: 500,
      originalPrice: null,
      available: true,
    },
    {
      id: 4,
      title: 'Gym Membership',
      location: 'New York',
      details: 'Join our gym with state-of-the-art equipment and professional trainers.',
      image: '../images/Gym.webp',
      score: 9.0,
      price: 50,
      originalPrice: 60,
      available: true,
    },
    {
      id: 5,
      title: 'Rent Football Pitch',
      location: 'Boston',
      details: 'Rent a professional football pitch for your matches and practice.',
      image: '/images/Football.jpg',
      score: 9.5,
      price: 100,
      originalPrice: null,
      available: true,
    },
    {
      id: 6,
      title: 'Swimming Lessons with Kate Zahaeres',
      location: 'Miami',
      details: 'Take swimming lessons with professional coach Kate Zahaeres.',
      image: '/images/Swimming.webp',
      score: 9.8,
      price: 35,
      originalPrice: 40,
      available: false,
    },
  ];

  export default servicesData;